
ByteIntMap.obj: \
	ByteIntMap.cpp \
    "ByteIntMap.h" \
    "$(includedir)\Freeze\Map.h" \
    "$(includedir)\Freeze\DB.h" \
    "$(includedir)\Freeze\Exception.h" \
    "$(includedir)\Freeze\Connection.h" \
    "$(includedir)\Freeze\Transaction.h" \

IntIdentityMap.obj: \
	IntIdentityMap.cpp \
    "IntIdentityMap.h" \
    "$(includedir)\Freeze\Map.h" \
    "$(includedir)\Freeze\DB.h" \
    "$(includedir)\Freeze\Exception.h" \
    "$(includedir)\Freeze\Connection.h" \
    "$(includedir)\Freeze\Transaction.h" \

IntIdentityMapWithIndex.obj: \
	IntIdentityMapWithIndex.cpp \
    "IntIdentityMapWithIndex.h" \
    "$(includedir)\Freeze\Map.h" \
    "$(includedir)\Freeze\DB.h" \
    "$(includedir)\Freeze\Exception.h" \
    "$(includedir)\Freeze\Connection.h" \
    "$(includedir)\Freeze\Transaction.h" \

SortedMap.obj: \
	SortedMap.cpp \
    "SortedMap.h" \
    "$(includedir)\Freeze\Map.h" \
    "$(includedir)\Freeze\DB.h" \
    "$(includedir)\Freeze\Exception.h" \
    "$(includedir)\Freeze\Connection.h" \
    "$(includedir)\Freeze\Transaction.h" \

WstringWstringMap.obj: \
	WstringWstringMap.cpp \
    "WstringWstringMap.h" \
    "$(includedir)\Freeze\Map.h" \
    "$(includedir)\Freeze\DB.h" \
    "$(includedir)\Freeze\Exception.h" \
    "$(includedir)\Freeze\Connection.h" \
    "$(includedir)\Freeze\Transaction.h" \

Client.obj: \
	Client.cpp \
    "$(includedir)\Freeze\Freeze.h" \
    "$(includedir)\Freeze\Initialize.h" \
    "$(includedir)\Freeze\EvictorF.h" \
    "$(includedir)\Freeze\ConnectionF.h" \
    "$(includedir)\Freeze\Index.h" \
    "$(includedir)\Freeze\DB.h" \
    "$(includedir)\Freeze\Transaction.h" \
    "$(includedir)\Freeze\BackgroundSaveEvictor.h" \
    "$(includedir)\Freeze\Evictor.h" \
    "$(includedir)\Freeze\Exception.h" \
    "$(includedir)\Freeze\TransactionalEvictor.h" \
    "$(includedir)\Freeze\Map.h" \
    "$(includedir)\Freeze\Connection.h" \
    "$(includedir)\Freeze\TransactionHolder.h" \
    "$(includedir)\Freeze\Catalog.h" \
    "$(includedir)\Freeze\CatalogData.h" \
    "$(includedir)\Freeze\AbstractMutex.h" \
    "$(includedir)\Freeze\Cache.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "ByteIntMap.h" \
    "IntIdentityMap.h" \
    "IntIdentityMapWithIndex.h" \
    "SortedMap.h" \
    "WstringWstringMap.h" \
